@echo off
cd /d "%~dp0"
echo Checking ExploreScreen.js...
node -c src/screens/ExploreScreen.js
echo Checking ReelsScreen.js...
node -c src/screens/ReelsScreen.js
echo Checking PlayerContext.js...
node -c src/context/PlayerContext.js
echo Checking ApiService.js...
node -c src/services/ApiService.js
echo Checking App.js...
node -c App.js
echo Done.
